oauth2:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-url: ${GOOGLE_TOKEN_URL}
    user-info-url: ${GOOGLE_USER_INFO_URL}
    redirect-uri: ${GOOGLE_REDIRECT_URI}

  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    token-url: ${KAKAO_TOKEN_URL}
    user-info-url: ${KAKAO_USER_INFO_URL}
    redirect-uri: ${KAKAO_REDIRECT_URI}

token:
  secret: ${TOKEN_SECRET}
  access-token-expiration-time: 900000
  refresh-token-expiration-time: 1209600000


# UserDetailsService 빈 자동등록을 해제하여 자동으로 생성되는 보안 비밀번호와 관련된 경고 메시지가 표시되지 않도록 한다.
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration